on:
  schedule:
    - cron: "0 7 * * *"

jobs:
  import-data:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rvest 
            any::stringr
            any::dplyr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript --no-save --verbose finect.R

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'updating' || echo "No changes to commit"
          git push || echo "No changes to commit"
